name: aseprite

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to build, leave empty for latest"
        required: false

jobs:
  build:
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        id: build
        shell: cmd
        run: call build.cmd
        env:
          ASEPRITE_VERSION: ${{ github.event.inputs.version }}

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-${{ steps.build.outputs.ASEPRITE_VERSION }}
          path: github
          if-no-files-found: error

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build \
            libx11-dev libxcursor-dev libgl1-mesa-dev libfontconfig1-dev \
            libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev libxxf86vm-dev \
            libxext-dev libpng-dev libjpeg-dev libtiff-dev libwebp-dev \
            libfreetype6-dev libcurl4-openssl-dev

      - name: Build
        id: build
        run: |
          chmod +x ./build.sh
          ./build.sh
        env:
          ASEPRITE_VERSION: ${{ github.event.inputs.version }}

      - name: Archive
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-linux-${{ steps.build.outputs.ASEPRITE_VERSION || 'latest' }}
          path: github
          if-no-files-found: error
